### ISSUE TITLE
Suggested Fixes

### ISSUE THREAD

**Issue by iracooke** [TS404/AlikeAlignmentAligner#40]
- [x] Emit sensible error if alignments are of different lengths
- [x] Consider adding functionality estimate sum-of-pairs true positive (SPFP) and sum-of-pairs false negative (SPFN) scores of the estimated alignment on a per column basis
- [x] Consider ordering based on common names between MSAs rather than requiring MSAs to be in a fixed order

**Comment by TS404** [comment]
The alignment lengths isn't really a problem. There was evidently some copy/paste error on the short alignment test.

**Comment by TS404** [comment]
comparison alignment sequences now ordered relative to reference alignment sequences. Names do not have to be identical. Just sequences.

**Comment by iracooke** [comment]
Beautiful!  Of course .. that’s the right way to do it
